from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DatCrt(object):
    def setupUi(self, DatCrt):
        DatCrt.setObjectName("DatCrt")
        DatCrt.resize(656, 673)
        DatCrt.setMinimumSize(QtCore.QSize(656, 673))
        DatCrt.setMaximumSize(QtCore.QSize(656, 673))
        self.CentWdgt = QtWidgets.QWidget(DatCrt)
        self.CentWdgt.setObjectName("CentWdgt")
        self.CentLay = QtWidgets.QVBoxLayout(self.CentWdgt)
        self.CentLay.setObjectName("CentLay")
        self.TrnSetDef = QtWidgets.QGroupBox(self.CentWdgt)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.TrnSetDef.setFont(font)
        self.TrnSetDef.setObjectName("TrnSetDef")
        self.TrnSetLay = QtWidgets.QGridLayout(self.TrnSetDef)
        self.TrnSetLay.setHorizontalSpacing(15)
        self.TrnSetLay.setObjectName("TrnSetLay")
        self.TrnSetCSVLbl = QtWidgets.QLabel(self.TrnSetDef)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.TrnSetCSVLbl.setFont(font)
        self.TrnSetCSVLbl.setObjectName("TrnSetCSVLbl")
        self.TrnSetLay.addWidget(self.TrnSetCSVLbl, 0, 0, 1, 1)
        self.TrnCrtLbl = QtWidgets.QLabel(self.TrnSetDef)
        self.TrnCrtLbl.setMinimumSize(QtCore.QSize(80, 0))
        self.TrnCrtLbl.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.TrnCrtLbl.setFont(font)
        self.TrnCrtLbl.setObjectName("TrnCrtLbl")
        self.TrnSetLay.addWidget(self.TrnCrtLbl, 0, 1, 1, 1)
        self.TrnSetCSVFrm = QtWidgets.QFrame(self.TrnSetDef)
        self.TrnSetCSVFrm.setMinimumSize(QtCore.QSize(0, 30))
        self.TrnSetCSVFrm.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.TrnSetCSVFrm.setFont(font)
        self.TrnSetCSVFrm.setObjectName("TrnSetCSVFrm")
        self.TrnSetCSVLay = QtWidgets.QHBoxLayout(self.TrnSetCSVFrm)
        self.TrnSetCSVLay.setContentsMargins(0, 0, 0, 0)
        self.TrnSetCSVLay.setSpacing(5)
        self.TrnSetCSVLay.setObjectName("TrnSetCSVLay")
        self.TrnSetCSV = QtWidgets.QLineEdit(self.TrnSetCSVFrm)
        self.TrnSetCSV.setMinimumSize(QtCore.QSize(0, 20))
        self.TrnSetCSV.setMaximumSize(QtCore.QSize(16777215, 20))
        self.TrnSetCSV.setObjectName("TrnSetCSV")
        self.TrnSetCSVLay.addWidget(self.TrnSetCSV)
        self.TrnSetCSVBtn = QtWidgets.QPushButton(self.TrnSetCSVFrm)
        self.TrnSetCSVBtn.setMinimumSize(QtCore.QSize(20, 20))
        self.TrnSetCSVBtn.setMaximumSize(QtCore.QSize(20, 20))
        self.TrnSetCSVBtn.setObjectName("TrnSetCSVBtn")
        self.TrnSetCSVLay.addWidget(self.TrnSetCSVBtn)
        self.TrnSetLay.addWidget(self.TrnSetCSVFrm, 1, 0, 1, 1)
        self.TrnRdbLay = QtWidgets.QHBoxLayout()
        self.TrnRdbLay.setSpacing(0)
        self.TrnRdbLay.setObjectName("TrnRdbLay")
        self.TrnRdbY = QtWidgets.QRadioButton(self.TrnSetDef)
        self.TrnRdbY.setMinimumSize(QtCore.QSize(35, 0))
        self.TrnRdbY.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.TrnRdbY.setFont(font)
        self.TrnRdbY.setChecked(True)
        self.TrnRdbY.setObjectName("TrnRdbY")
        self.TrnBtnGrp = QtWidgets.QButtonGroup(DatCrt)
        self.TrnBtnGrp.setObjectName("TrnBtnGrp")
        self.TrnBtnGrp.addButton(self.TrnRdbY)
        self.TrnRdbLay.addWidget(self.TrnRdbY)
        self.TrnRdbN = QtWidgets.QRadioButton(self.TrnSetDef)
        self.TrnRdbN.setMinimumSize(QtCore.QSize(35, 0))
        self.TrnRdbN.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.TrnRdbN.setFont(font)
        self.TrnRdbN.setObjectName("TrnRdbN")
        self.TrnBtnGrp.addButton(self.TrnRdbN)
        self.TrnRdbLay.addWidget(self.TrnRdbN)
        self.TrnSetLay.addLayout(self.TrnRdbLay, 1, 1, 1, 1)
        self.CentLay.addWidget(self.TrnSetDef)
        self.VldSetDef = QtWidgets.QGroupBox(self.CentWdgt)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.VldSetDef.setFont(font)
        self.VldSetDef.setObjectName("VldSetDef")
        self.VldSetLay = QtWidgets.QGridLayout(self.VldSetDef)
        self.VldSetLay.setHorizontalSpacing(15)
        self.VldSetLay.setObjectName("VldSetLay")
        self.VldSetCSVFrm = QtWidgets.QFrame(self.VldSetDef)
        self.VldSetCSVFrm.setMinimumSize(QtCore.QSize(0, 30))
        self.VldSetCSVFrm.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.VldSetCSVFrm.setFont(font)
        self.VldSetCSVFrm.setObjectName("VldSetCSVFrm")
        self.VldSetCSVLay = QtWidgets.QHBoxLayout(self.VldSetCSVFrm)
        self.VldSetCSVLay.setContentsMargins(0, 0, 0, 0)
        self.VldSetCSVLay.setSpacing(5)
        self.VldSetCSVLay.setObjectName("VldSetCSVLay")
        self.VldSetCSV = QtWidgets.QLineEdit(self.VldSetCSVFrm)
        self.VldSetCSV.setMinimumSize(QtCore.QSize(0, 20))
        self.VldSetCSV.setMaximumSize(QtCore.QSize(16777215, 20))
        self.VldSetCSV.setObjectName("VldSetCSV")
        self.VldSetCSVLay.addWidget(self.VldSetCSV)
        self.VldSetCSVBtn = QtWidgets.QPushButton(self.VldSetCSVFrm)
        self.VldSetCSVBtn.setMinimumSize(QtCore.QSize(20, 20))
        self.VldSetCSVBtn.setMaximumSize(QtCore.QSize(20, 20))
        self.VldSetCSVBtn.setObjectName("VldSetCSVBtn")
        self.VldSetCSVLay.addWidget(self.VldSetCSVBtn)
        self.VldSetLay.addWidget(self.VldSetCSVFrm, 1, 0, 1, 1)
        self.VldSetCSVLbl = QtWidgets.QLabel(self.VldSetDef)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.VldSetCSVLbl.setFont(font)
        self.VldSetCSVLbl.setObjectName("VldSetCSVLbl")
        self.VldSetLay.addWidget(self.VldSetCSVLbl, 0, 0, 1, 1)
        self.VldCrtLbl = QtWidgets.QLabel(self.VldSetDef)
        self.VldCrtLbl.setMinimumSize(QtCore.QSize(80, 0))
        self.VldCrtLbl.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.VldCrtLbl.setFont(font)
        self.VldCrtLbl.setObjectName("VldCrtLbl")
        self.VldSetLay.addWidget(self.VldCrtLbl, 0, 1, 1, 1)
        self.VldRdbLay = QtWidgets.QHBoxLayout()
        self.VldRdbLay.setSpacing(0)
        self.VldRdbLay.setObjectName("VldRdbLay")
        self.VldRdbY = QtWidgets.QRadioButton(self.VldSetDef)
        self.VldRdbY.setMinimumSize(QtCore.QSize(35, 0))
        self.VldRdbY.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.VldRdbY.setFont(font)
        self.VldRdbY.setChecked(True)
        self.VldRdbY.setObjectName("VldRdbY")
        self.VldBtnGrp = QtWidgets.QButtonGroup(DatCrt)
        self.VldBtnGrp.setObjectName("VldBtnGrp")
        self.VldBtnGrp.addButton(self.VldRdbY)
        self.VldRdbLay.addWidget(self.VldRdbY)
        self.VldRdbN = QtWidgets.QRadioButton(self.VldSetDef)
        self.VldRdbN.setMinimumSize(QtCore.QSize(35, 0))
        self.VldRdbN.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.VldRdbN.setFont(font)
        self.VldRdbN.setObjectName("VldRdbN")
        self.VldBtnGrp.addButton(self.VldRdbN)
        self.VldRdbLay.addWidget(self.VldRdbN)
        self.VldSetLay.addLayout(self.VldRdbLay, 1, 1, 1, 1)
        self.CentLay.addWidget(self.VldSetDef)
        self.TstSetDef = QtWidgets.QGroupBox(self.CentWdgt)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.TstSetDef.setFont(font)
        self.TstSetDef.setObjectName("TstSetDef")
        self.TstSetLay = QtWidgets.QGridLayout(self.TstSetDef)
        self.TstSetLay.setHorizontalSpacing(15)
        self.TstSetLay.setObjectName("TstSetLay")
        self.TstCrtLbl = QtWidgets.QLabel(self.TstSetDef)
        self.TstCrtLbl.setMinimumSize(QtCore.QSize(80, 0))
        self.TstCrtLbl.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.TstCrtLbl.setFont(font)
        self.TstCrtLbl.setObjectName("TstCrtLbl")
        self.TstSetLay.addWidget(self.TstCrtLbl, 0, 1, 1, 1)
        self.TstSetCSVLbl = QtWidgets.QLabel(self.TstSetDef)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.TstSetCSVLbl.setFont(font)
        self.TstSetCSVLbl.setObjectName("TstSetCSVLbl")
        self.TstSetLay.addWidget(self.TstSetCSVLbl, 0, 0, 1, 1)
        self.TstSetCSVFrm = QtWidgets.QFrame(self.TstSetDef)
        self.TstSetCSVFrm.setMinimumSize(QtCore.QSize(0, 30))
        self.TstSetCSVFrm.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.TstSetCSVFrm.setFont(font)
        self.TstSetCSVFrm.setObjectName("TstSetCSVFrm")
        self.TstSetCSVLay = QtWidgets.QHBoxLayout(self.TstSetCSVFrm)
        self.TstSetCSVLay.setContentsMargins(0, 0, 0, 0)
        self.TstSetCSVLay.setSpacing(5)
        self.TstSetCSVLay.setObjectName("TstSetCSVLay")
        self.TstSetCSV = QtWidgets.QLineEdit(self.TstSetCSVFrm)
        self.TstSetCSV.setMinimumSize(QtCore.QSize(0, 20))
        self.TstSetCSV.setMaximumSize(QtCore.QSize(16777215, 20))
        self.TstSetCSV.setObjectName("TstSetCSV")
        self.TstSetCSVLay.addWidget(self.TstSetCSV)
        self.TstSetCSVBtn = QtWidgets.QPushButton(self.TstSetCSVFrm)
        self.TstSetCSVBtn.setMinimumSize(QtCore.QSize(20, 20))
        self.TstSetCSVBtn.setMaximumSize(QtCore.QSize(20, 20))
        self.TstSetCSVBtn.setObjectName("TstSetCSVBtn")
        self.TstSetCSVLay.addWidget(self.TstSetCSVBtn)
        self.TstSetLay.addWidget(self.TstSetCSVFrm, 1, 0, 1, 1)
        self.TstRdbLay = QtWidgets.QHBoxLayout()
        self.TstRdbLay.setSpacing(0)
        self.TstRdbLay.setObjectName("TstRdbLay")
        self.TstRdbY = QtWidgets.QRadioButton(self.TstSetDef)
        self.TstRdbY.setMinimumSize(QtCore.QSize(35, 0))
        self.TstRdbY.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.TstRdbY.setFont(font)
        self.TstRdbY.setChecked(True)
        self.TstRdbY.setObjectName("TstRdbY")
        self.TstBtnGrp = QtWidgets.QButtonGroup(DatCrt)
        self.TstBtnGrp.setObjectName("TstBtnGrp")
        self.TstBtnGrp.addButton(self.TstRdbY)
        self.TstRdbLay.addWidget(self.TstRdbY)
        self.TstRdbN = QtWidgets.QRadioButton(self.TstSetDef)
        self.TstRdbN.setMinimumSize(QtCore.QSize(35, 0))
        self.TstRdbN.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.TstRdbN.setFont(font)
        self.TstRdbN.setObjectName("TstRdbN")
        self.TstBtnGrp.addButton(self.TstRdbN)
        self.TstRdbLay.addWidget(self.TstRdbN)
        self.TstSetLay.addLayout(self.TstRdbLay, 1, 1, 1, 1)
        self.CentLay.addWidget(self.TstSetDef)
        self.TagSet = QtWidgets.QGroupBox(self.CentWdgt)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.TagSet.setFont(font)
        self.TagSet.setObjectName("TagSet")
        self.TagSetLay = QtWidgets.QVBoxLayout(self.TagSet)
        self.TagSetLay.setObjectName("TagSetLay")
        self.LblLstLay = QtWidgets.QVBoxLayout()
        self.LblLstLay.setSpacing(0)
        self.LblLstLay.setObjectName("LblLstLay")
        self.LblLstLbl = QtWidgets.QLabel(self.TagSet)
        self.LblLstLbl.setMinimumSize(QtCore.QSize(0, 20))
        self.LblLstLbl.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.LblLstLbl.setFont(font)
        self.LblLstLbl.setObjectName("LblLstLbl")
        self.LblLstLay.addWidget(self.LblLstLbl)
        self.LblLst = QtWidgets.QLineEdit(self.TagSet)
        self.LblLst.setMinimumSize(QtCore.QSize(0, 20))
        self.LblLst.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.LblLst.setFont(font)
        self.LblLst.setObjectName("LblLst")
        self.LblLstLay.addWidget(self.LblLst)
        self.TagSetLay.addLayout(self.LblLstLay)
        self.SaveLay = QtWidgets.QHBoxLayout()
        self.SaveLay.setSpacing(5)
        self.SaveLay.setObjectName("SaveLay")
        self.GrpLstLay = QtWidgets.QVBoxLayout()
        self.GrpLstLay.setSpacing(0)
        self.GrpLstLay.setObjectName("GrpLstLay")
        self.GrpLstLbl = QtWidgets.QLabel(self.TagSet)
        self.GrpLstLbl.setMinimumSize(QtCore.QSize(0, 20))
        self.GrpLstLbl.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.GrpLstLbl.setFont(font)
        self.GrpLstLbl.setObjectName("GrpLstLbl")
        self.GrpLstLay.addWidget(self.GrpLstLbl)
        self.GrpLst = QtWidgets.QLineEdit(self.TagSet)
        self.GrpLst.setMinimumSize(QtCore.QSize(0, 20))
        self.GrpLst.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.GrpLst.setFont(font)
        self.GrpLst.setObjectName("GrpLst")
        self.GrpLstLay.addWidget(self.GrpLst)
        self.SaveLay.addLayout(self.GrpLstLay)
        self.LblSaveLay = QtWidgets.QVBoxLayout()
        self.LblSaveLay.setSpacing(5)
        self.LblSaveLay.setObjectName("LblSaveLay")
        self.KpDumCkb = QtWidgets.QCheckBox(self.TagSet)
        self.KpDumCkb.setMinimumSize(QtCore.QSize(180, 20))
        self.KpDumCkb.setMaximumSize(QtCore.QSize(180, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.KpDumCkb.setFont(font)
        self.KpDumCkb.setObjectName("KpDumCkb")
        self.LblSaveLay.addWidget(self.KpDumCkb)
        self.FrcTstCkb = QtWidgets.QCheckBox(self.TagSet)
        self.FrcTstCkb.setMinimumSize(QtCore.QSize(180, 20))
        self.FrcTstCkb.setMaximumSize(QtCore.QSize(180, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.FrcTstCkb.setFont(font)
        self.FrcTstCkb.setChecked(True)
        self.FrcTstCkb.setObjectName("FrcTstCkb")
        self.LblSaveLay.addWidget(self.FrcTstCkb)
        self.SaveLay.addLayout(self.LblSaveLay)
        self.TagSetLay.addLayout(self.SaveLay)
        self.CentLay.addWidget(self.TagSet)
        self.ProcSet = QtWidgets.QGroupBox(self.CentWdgt)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ProcSet.setFont(font)
        self.ProcSet.setObjectName("ProcSet")
        self.ProcSetLay = QtWidgets.QHBoxLayout(self.ProcSet)
        self.ProcSetLay.setObjectName("ProcSetLay")
        self.ProcMainSet = QtWidgets.QFrame(self.ProcSet)
        self.ProcMainSet.setMinimumSize(QtCore.QSize(150, 90))
        self.ProcMainSet.setMaximumSize(QtCore.QSize(150, 90))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ProcMainSet.setFont(font)
        self.ProcMainSet.setFrameShape(QtWidgets.QFrame.Box)
        self.ProcMainSet.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ProcMainSet.setObjectName("ProcMainSet")
        self.AugMainSetLay = QtWidgets.QVBoxLayout(self.ProcMainSet)
        self.AugMainSetLay.setContentsMargins(5, 0, 5, 5)
        self.AugMainSetLay.setSpacing(0)
        self.AugMainSetLay.setObjectName("AugMainSetLay")
        self.AugNoLbl = QtWidgets.QLabel(self.ProcMainSet)
        self.AugNoLbl.setObjectName("AugNoLbl")
        self.AugMainSetLay.addWidget(self.AugNoLbl)
        self.AugNoSpb = QtWidgets.QSpinBox(self.ProcMainSet)
        self.AugNoSpb.setMinimumSize(QtCore.QSize(0, 20))
        self.AugNoSpb.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.AugNoSpb.setFont(font)
        self.AugNoSpb.setMinimum(0)
        self.AugNoSpb.setMaximum(128)
        self.AugNoSpb.setProperty("value", 8)
        self.AugNoSpb.setObjectName("AugNoSpb")
        self.AugMainSetLay.addWidget(self.AugNoSpb)
        self.ProcNoLbl = QtWidgets.QLabel(self.ProcMainSet)
        self.ProcNoLbl.setObjectName("ProcNoLbl")
        self.AugMainSetLay.addWidget(self.ProcNoLbl)
        self.ProcNoSpb = QtWidgets.QSpinBox(self.ProcMainSet)
        self.ProcNoSpb.setMinimumSize(QtCore.QSize(0, 20))
        self.ProcNoSpb.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ProcNoSpb.setFont(font)
        self.ProcNoSpb.setMinimum(1)
        self.ProcNoSpb.setMaximum(128)
        self.ProcNoSpb.setProperty("value", 8)
        self.ProcNoSpb.setObjectName("ProcNoSpb")
        self.AugMainSetLay.addWidget(self.ProcNoSpb)
        self.ProcSetLay.addWidget(self.ProcMainSet)
        self.LblSetFrm = QtWidgets.QFrame(self.ProcSet)
        self.LblSetFrm.setMinimumSize(QtCore.QSize(150, 90))
        self.LblSetFrm.setMaximumSize(QtCore.QSize(150, 90))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.LblSetFrm.setFont(font)
        self.LblSetFrm.setFrameShape(QtWidgets.QFrame.Box)
        self.LblSetFrm.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.LblSetFrm.setObjectName("LblSetFrm")
        self.LblSetLay = QtWidgets.QVBoxLayout(self.LblSetFrm)
        self.LblSetLay.setContentsMargins(5, 5, 5, 5)
        self.LblSetLay.setSpacing(3)
        self.LblSetLay.setObjectName("LblSetLay")
        self.LblTypValLay = QtWidgets.QHBoxLayout()
        self.LblTypValLay.setSpacing(5)
        self.LblTypValLay.setObjectName("LblTypValLay")
        self.LblTypJS = QtWidgets.QRadioButton(self.LblSetFrm)
        self.LblTypJS.setMinimumSize(QtCore.QSize(50, 20))
        self.LblTypJS.setMaximumSize(QtCore.QSize(50, 20))
        self.LblTypJS.setChecked(True)
        self.LblTypJS.setObjectName("LblTypJS")
        self.LblTypBtnGrp = QtWidgets.QButtonGroup(DatCrt)
        self.LblTypBtnGrp.setObjectName("LblTypBtnGrp")
        self.LblTypBtnGrp.addButton(self.LblTypJS)
        self.LblTypValLay.addWidget(self.LblTypJS)
        self.LblTypHM = QtWidgets.QRadioButton(self.LblSetFrm)
        self.LblTypHM.setMinimumSize(QtCore.QSize(70, 20))
        self.LblTypHM.setMaximumSize(QtCore.QSize(70, 20))
        self.LblTypHM.setObjectName("LblTypHM")
        self.LblTypBtnGrp.addButton(self.LblTypHM)
        self.LblTypValLay.addWidget(self.LblTypHM)
        self.LblSetLay.addLayout(self.LblTypValLay)
        self.LblSetLn = QtWidgets.QFrame(self.LblSetFrm)
        self.LblSetLn.setFrameShape(QtWidgets.QFrame.HLine)
        self.LblSetLn.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.LblSetLn.setObjectName("LblSetLn")
        self.LblSetLay.addWidget(self.LblSetLn)
        self.HMSetLay = QtWidgets.QGridLayout()
        self.HMSetLay.setHorizontalSpacing(5)
        self.HMSetLay.setVerticalSpacing(2)
        self.HMSetLay.setObjectName("HMSetLay")
        self.HMPeakLbl = QtWidgets.QLabel(self.LblSetFrm)
        self.HMPeakLbl.setEnabled(False)
        self.HMPeakLbl.setMinimumSize(QtCore.QSize(0, 20))
        self.HMPeakLbl.setMaximumSize(QtCore.QSize(16777215, 20))
        self.HMPeakLbl.setObjectName("HMPeakLbl")
        self.HMSetLay.addWidget(self.HMPeakLbl, 0, 0, 1, 1)
        self.HMSeqLbl = QtWidgets.QLabel(self.LblSetFrm)
        self.HMSeqLbl.setEnabled(False)
        self.HMSeqLbl.setMinimumSize(QtCore.QSize(0, 20))
        self.HMSeqLbl.setMaximumSize(QtCore.QSize(16777215, 20))
        self.HMSeqLbl.setObjectName("HMSeqLbl")
        self.HMSetLay.addWidget(self.HMSeqLbl, 0, 1, 1, 1)
        self.HMPeak = QtWidgets.QDoubleSpinBox(self.LblSetFrm)
        self.HMPeak.setEnabled(False)
        self.HMPeak.setMinimumSize(QtCore.QSize(50, 20))
        self.HMPeak.setMaximumSize(QtCore.QSize(50, 20))
        self.HMPeak.setMinimum(1.0)
        self.HMPeak.setMaximum(128.0)
        self.HMPeak.setProperty("value", 16.0)
        self.HMPeak.setObjectName("HMPeak")
        self.HMSetLay.addWidget(self.HMPeak, 1, 0, 1, 1)
        self.HMSeqCkb = QtWidgets.QCheckBox(self.LblSetFrm)
        self.HMSeqCkb.setEnabled(False)
        self.HMSeqCkb.setMinimumSize(QtCore.QSize(70, 20))
        self.HMSeqCkb.setMaximumSize(QtCore.QSize(70, 20))
        self.HMSeqCkb.setObjectName("HMSeqCkb")
        self.HMSetLay.addWidget(self.HMSeqCkb, 1, 1, 1, 1)
        self.LblSetLay.addLayout(self.HMSetLay)
        self.ProcSetLay.addWidget(self.LblSetFrm)
        self.RndFlpFrm = QtWidgets.QFrame(self.ProcSet)
        self.RndFlpFrm.setMinimumSize(QtCore.QSize(150, 90))
        self.RndFlpFrm.setMaximumSize(QtCore.QSize(150, 90))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.RndFlpFrm.setFont(font)
        self.RndFlpFrm.setFrameShape(QtWidgets.QFrame.Box)
        self.RndFlpFrm.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.RndFlpFrm.setObjectName("RndFlpFrm")
        self.RndFlpLay = QtWidgets.QVBoxLayout(self.RndFlpFrm)
        self.RndFlpLay.setContentsMargins(5, 5, 5, 5)
        self.RndFlpLay.setSpacing(3)
        self.RndFlpLay.setObjectName("RndFlpLay")
        self.RndFlpCkb = QtWidgets.QCheckBox(self.RndFlpFrm)
        self.RndFlpCkb.setMinimumSize(QtCore.QSize(0, 20))
        self.RndFlpCkb.setMaximumSize(QtCore.QSize(16777215, 20))
        self.RndFlpCkb.setChecked(True)
        self.RndFlpCkb.setObjectName("RndFlpCkb")
        self.RndFlpLay.addWidget(self.RndFlpCkb)
        self.RndFlpLn = QtWidgets.QFrame(self.RndFlpFrm)
        self.RndFlpLn.setFrameShape(QtWidgets.QFrame.HLine)
        self.RndFlpLn.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.RndFlpLn.setObjectName("RndFlpLn")
        self.RndFlpLay.addWidget(self.RndFlpLn)
        self.RndFlpAxLay = QtWidgets.QVBoxLayout()
        self.RndFlpAxLay.setSpacing(2)
        self.RndFlpAxLay.setObjectName("RndFlpAxLay")
        self.RndFlpAxLbl = QtWidgets.QLabel(self.RndFlpFrm)
        self.RndFlpAxLbl.setEnabled(True)
        self.RndFlpAxLbl.setMinimumSize(QtCore.QSize(0, 20))
        self.RndFlpAxLbl.setMaximumSize(QtCore.QSize(16777215, 20))
        self.RndFlpAxLbl.setObjectName("RndFlpAxLbl")
        self.RndFlpAxLay.addWidget(self.RndFlpAxLbl)
        self.RndFlpAxValLay = QtWidgets.QHBoxLayout()
        self.RndFlpAxValLay.setSpacing(5)
        self.RndFlpAxValLay.setObjectName("RndFlpAxValLay")
        self.RndFlpX = QtWidgets.QCheckBox(self.RndFlpFrm)
        self.RndFlpX.setMinimumSize(QtCore.QSize(30, 20))
        self.RndFlpX.setMaximumSize(QtCore.QSize(30, 20))
        self.RndFlpX.setChecked(True)
        self.RndFlpX.setObjectName("RndFlpX")
        self.RndFlpAxValLay.addWidget(self.RndFlpX)
        self.RndFlpY = QtWidgets.QCheckBox(self.RndFlpFrm)
        self.RndFlpY.setMinimumSize(QtCore.QSize(30, 20))
        self.RndFlpY.setMaximumSize(QtCore.QSize(30, 20))
        self.RndFlpY.setChecked(True)
        self.RndFlpY.setObjectName("RndFlpY")
        self.RndFlpAxValLay.addWidget(self.RndFlpY)
        self.RndFlpXY = QtWidgets.QCheckBox(self.RndFlpFrm)
        self.RndFlpXY.setMinimumSize(QtCore.QSize(35, 20))
        self.RndFlpXY.setMaximumSize(QtCore.QSize(35, 20))
        self.RndFlpXY.setChecked(True)
        self.RndFlpXY.setObjectName("RndFlpXY")
        self.RndFlpAxValLay.addWidget(self.RndFlpXY)
        self.RndFlpAxLay.addLayout(self.RndFlpAxValLay)
        self.RndFlpLay.addLayout(self.RndFlpAxLay)
        self.ProcSetLay.addWidget(self.RndFlpFrm)
        self.RndRotFrm = QtWidgets.QFrame(self.ProcSet)
        self.RndRotFrm.setMinimumSize(QtCore.QSize(150, 90))
        self.RndRotFrm.setMaximumSize(QtCore.QSize(150, 90))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.RndRotFrm.setFont(font)
        self.RndRotFrm.setFrameShape(QtWidgets.QFrame.Box)
        self.RndRotFrm.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.RndRotFrm.setObjectName("RndRotFrm")
        self.RndRotLay = QtWidgets.QVBoxLayout(self.RndRotFrm)
        self.RndRotLay.setContentsMargins(5, 5, 5, 5)
        self.RndRotLay.setSpacing(3)
        self.RndRotLay.setObjectName("RndRotLay")
        self.RndRotCkb = QtWidgets.QCheckBox(self.RndRotFrm)
        self.RndRotCkb.setMinimumSize(QtCore.QSize(0, 20))
        self.RndRotCkb.setMaximumSize(QtCore.QSize(16777215, 20))
        self.RndRotCkb.setChecked(True)
        self.RndRotCkb.setObjectName("RndRotCkb")
        self.RndRotLay.addWidget(self.RndRotCkb)
        self.RndRotLn = QtWidgets.QFrame(self.RndRotFrm)
        self.RndRotLn.setFrameShape(QtWidgets.QFrame.HLine)
        self.RndRotLn.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.RndRotLn.setObjectName("RndRotLn")
        self.RndRotLay.addWidget(self.RndRotLn)
        self.RndRotAgLay = QtWidgets.QVBoxLayout()
        self.RndRotAgLay.setSpacing(2)
        self.RndRotAgLay.setObjectName("RndRotAgLay")
        self.RndRotAgLbl = QtWidgets.QLabel(self.RndRotFrm)
        self.RndRotAgLbl.setMinimumSize(QtCore.QSize(0, 20))
        self.RndRotAgLbl.setMaximumSize(QtCore.QSize(16777215, 20))
        self.RndRotAgLbl.setObjectName("RndRotAgLbl")
        self.RndRotAgLay.addWidget(self.RndRotAgLbl)
        self.RndRotAgValLay = QtWidgets.QHBoxLayout()
        self.RndRotAgValLay.setSpacing(5)
        self.RndRotAgValLay.setObjectName("RndRotAgValLay")
        self.RndRotMin = QtWidgets.QDoubleSpinBox(self.RndRotFrm)
        self.RndRotMin.setMinimumSize(QtCore.QSize(60, 20))
        self.RndRotMin.setMaximumSize(QtCore.QSize(60, 20))
        self.RndRotMin.setMinimum(-360.0)
        self.RndRotMin.setMaximum(360.0)
        self.RndRotMin.setSingleStep(10.0)
        self.RndRotMin.setProperty("value", -10.0)
        self.RndRotMin.setObjectName("RndRotMin")
        self.RndRotAgValLay.addWidget(self.RndRotMin)
        self.RndRotMax = QtWidgets.QDoubleSpinBox(self.RndRotFrm)
        self.RndRotMax.setMinimumSize(QtCore.QSize(60, 20))
        self.RndRotMax.setMaximumSize(QtCore.QSize(60, 20))
        self.RndRotMax.setMinimum(-360.0)
        self.RndRotMax.setMaximum(360.0)
        self.RndRotMax.setSingleStep(10.0)
        self.RndRotMax.setProperty("value", 10.0)
        self.RndRotMax.setObjectName("RndRotMax")
        self.RndRotAgValLay.addWidget(self.RndRotMax)
        self.RndRotAgLay.addLayout(self.RndRotAgValLay)
        self.RndRotLay.addLayout(self.RndRotAgLay)
        self.ProcSetLay.addWidget(self.RndRotFrm)
        self.CentLay.addWidget(self.ProcSet)
        self.OutSet = QtWidgets.QGroupBox(self.CentWdgt)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.OutSet.setFont(font)
        self.OutSet.setObjectName("OutSet")
        self.OutSetLay = QtWidgets.QHBoxLayout(self.OutSet)
        self.OutSetLay.setSpacing(10)
        self.OutSetLay.setObjectName("OutSetLay")
        self.ImgSize = QtWidgets.QFrame(self.OutSet)
        self.ImgSize.setMinimumSize(QtCore.QSize(150, 60))
        self.ImgSize.setMaximumSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ImgSize.setFont(font)
        self.ImgSize.setFrameShape(QtWidgets.QFrame.Box)
        self.ImgSize.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ImgSize.setObjectName("ImgSize")
        self.ImgSizeLay = QtWidgets.QGridLayout(self.ImgSize)
        self.ImgSizeLay.setContentsMargins(5, 5, 5, 5)
        self.ImgSizeLay.setSpacing(5)
        self.ImgSizeLay.setObjectName("ImgSizeLay")
        self.ImgWLbl = QtWidgets.QLabel(self.ImgSize)
        self.ImgWLbl.setMinimumSize(QtCore.QSize(75, 20))
        self.ImgWLbl.setMaximumSize(QtCore.QSize(75, 20))
        self.ImgWLbl.setObjectName("ImgWLbl")
        self.ImgSizeLay.addWidget(self.ImgWLbl, 0, 0, 1, 1)
        self.ImgW = QtWidgets.QSpinBox(self.ImgSize)
        self.ImgW.setMinimumSize(QtCore.QSize(60, 20))
        self.ImgW.setMaximumSize(QtCore.QSize(60, 20))
        self.ImgW.setMinimum(1)
        self.ImgW.setMaximum(999999999)
        self.ImgW.setProperty("value", 256)
        self.ImgW.setObjectName("ImgW")
        self.ImgSizeLay.addWidget(self.ImgW, 0, 1, 1, 1)
        self.ImgHLbl = QtWidgets.QLabel(self.ImgSize)
        self.ImgHLbl.setMinimumSize(QtCore.QSize(75, 20))
        self.ImgHLbl.setMaximumSize(QtCore.QSize(75, 20))
        self.ImgHLbl.setObjectName("ImgHLbl")
        self.ImgSizeLay.addWidget(self.ImgHLbl, 1, 0, 1, 1)
        self.ImgH = QtWidgets.QSpinBox(self.ImgSize)
        self.ImgH.setMinimumSize(QtCore.QSize(60, 20))
        self.ImgH.setMaximumSize(QtCore.QSize(60, 20))
        self.ImgH.setMinimum(1)
        self.ImgH.setMaximum(999999999)
        self.ImgH.setProperty("value", 256)
        self.ImgH.setObjectName("ImgH")
        self.ImgSizeLay.addWidget(self.ImgH, 1, 1, 1, 1)
        self.OutSetLay.addWidget(self.ImgSize)
        self.OutDirLay = QtWidgets.QVBoxLayout()
        self.OutDirLay.setSpacing(5)
        self.OutDirLay.setObjectName("OutDirLay")
        self.OutDirLbl = QtWidgets.QLabel(self.OutSet)
        self.OutDirLbl.setMinimumSize(QtCore.QSize(0, 20))
        self.OutDirLbl.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.OutDirLbl.setFont(font)
        self.OutDirLbl.setObjectName("OutDirLbl")
        self.OutDirLay.addWidget(self.OutDirLbl)
        self.OutDirFrm = QtWidgets.QFrame(self.OutSet)
        self.OutDirFrm.setMinimumSize(QtCore.QSize(0, 30))
        self.OutDirFrm.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.OutDirFrm.setFont(font)
        self.OutDirFrm.setObjectName("OutDirFrm")
        self.OutDirFrmLay = QtWidgets.QHBoxLayout(self.OutDirFrm)
        self.OutDirFrmLay.setContentsMargins(0, 0, 0, 0)
        self.OutDirFrmLay.setSpacing(5)
        self.OutDirFrmLay.setObjectName("OutDirFrmLay")
        self.OutDir = QtWidgets.QLineEdit(self.OutDirFrm)
        self.OutDir.setMinimumSize(QtCore.QSize(0, 20))
        self.OutDir.setMaximumSize(QtCore.QSize(16777215, 20))
        self.OutDir.setObjectName("OutDir")
        self.OutDirFrmLay.addWidget(self.OutDir)
        self.OutDirBtn = QtWidgets.QPushButton(self.OutDirFrm)
        self.OutDirBtn.setMinimumSize(QtCore.QSize(20, 20))
        self.OutDirBtn.setMaximumSize(QtCore.QSize(20, 20))
        self.OutDirBtn.setObjectName("OutDirBtn")
        self.OutDirFrmLay.addWidget(self.OutDirBtn)
        self.OutDirLay.addWidget(self.OutDirFrm)
        self.OutSetLay.addLayout(self.OutDirLay)
        self.CentLay.addWidget(self.OutSet)
        self.MainCtrlLay = QtWidgets.QHBoxLayout()
        self.MainCtrlLay.setSpacing(10)
        self.MainCtrlLay.setObjectName("MainCtrlLay")
        self.StartButton = QtWidgets.QPushButton(self.CentWdgt)
        self.StartButton.setMinimumSize(QtCore.QSize(100, 25))
        self.StartButton.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.StartButton.setFont(font)
        self.StartButton.setObjectName("StartButton")
        self.MainCtrlLay.addWidget(self.StartButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.MainCtrlLay.addItem(spacerItem)
        self.ExitButton = QtWidgets.QPushButton(self.CentWdgt)
        self.ExitButton.setMinimumSize(QtCore.QSize(100, 25))
        self.ExitButton.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ExitButton.setFont(font)
        self.ExitButton.setObjectName("ExitButton")
        self.MainCtrlLay.addWidget(self.ExitButton)
        self.CentLay.addLayout(self.MainCtrlLay)
        DatCrt.setCentralWidget(self.CentWdgt)

        self.retranslateUi(DatCrt)
        self.VldRdbY.clicked['bool'].connect(self.VldSetCSV.setEnabled)
        self.VldRdbY.clicked['bool'].connect(self.VldSetCSVBtn.setEnabled)
        self.VldRdbN.clicked['bool'].connect(self.VldSetCSV.setDisabled)
        self.VldRdbN.clicked['bool'].connect(self.VldSetCSVBtn.setDisabled)
        self.TstRdbY.clicked['bool'].connect(self.TstSetCSV.setEnabled)
        self.TstRdbY.clicked['bool'].connect(self.TstSetCSVBtn.setEnabled)
        self.TstRdbN.clicked['bool'].connect(self.TstSetCSV.setDisabled)
        self.TstRdbN.clicked['bool'].connect(self.TstSetCSVBtn.setDisabled)
        self.LblTypJS.clicked['bool'].connect(self.HMPeak.setDisabled)
        self.LblTypJS.clicked['bool'].connect(self.HMSeqCkb.setDisabled)
        self.LblTypHM.clicked['bool'].connect(self.HMPeak.setEnabled)
        self.LblTypHM.clicked['bool'].connect(self.HMSeqCkb.setEnabled)
        self.LblTypJS.clicked['bool'].connect(self.HMPeakLbl.setDisabled)
        self.LblTypJS.clicked['bool'].connect(self.HMSeqLbl.setDisabled)
        self.LblTypHM.clicked['bool'].connect(self.HMPeakLbl.setEnabled)
        self.LblTypHM.clicked['bool'].connect(self.HMSeqLbl.setEnabled)
        self.RndFlpCkb.clicked['bool'].connect(self.RndFlpX.setEnabled)
        self.RndFlpCkb.clicked['bool'].connect(self.RndFlpY.setEnabled)
        self.RndFlpCkb.clicked['bool'].connect(self.RndFlpXY.setEnabled)
        self.RndFlpCkb.clicked['bool'].connect(self.RndFlpAxLbl.setEnabled)
        self.RndRotCkb.clicked['bool'].connect(self.RndRotMin.setEnabled)
        self.RndRotCkb.clicked['bool'].connect(self.RndRotMax.setEnabled)
        self.RndRotCkb.clicked['bool'].connect(self.RndRotAgLbl.setEnabled)
        self.VldRdbY.clicked['bool'].connect(self.VldSetCSVLbl.setEnabled)
        self.VldRdbN.clicked['bool'].connect(self.VldSetCSVLbl.setDisabled)
        self.TstRdbY.clicked['bool'].connect(self.TstSetCSVLbl.setEnabled)
        self.TstRdbN.clicked['bool'].connect(self.TstSetCSVLbl.setDisabled)
        self.TrnRdbY.clicked['bool'].connect(self.TrnSetCSV.setEnabled)
        self.TrnRdbY.clicked['bool'].connect(self.TrnSetCSVBtn.setEnabled)
        self.TrnRdbN.clicked['bool'].connect(self.TrnSetCSV.setDisabled)
        self.TrnRdbN.clicked['bool'].connect(self.TrnSetCSVBtn.setDisabled)
        self.TrnRdbY.clicked['bool'].connect(self.TrnSetCSVLbl.setEnabled)
        self.TrnRdbN.clicked['bool'].connect(self.TrnSetCSVLbl.setDisabled)
        self.TrnRdbY.clicked['bool'].connect(self.RndFlpFrm.setEnabled)
        self.TrnRdbY.clicked['bool'].connect(self.RndRotFrm.setEnabled)
        self.TrnRdbN.clicked['bool'].connect(self.RndFlpFrm.setDisabled)
        self.TrnRdbN.clicked['bool'].connect(self.RndRotFrm.setDisabled)
        self.TrnRdbY.clicked['bool'].connect(self.AugNoLbl.setEnabled)
        self.TrnRdbY.clicked['bool'].connect(self.AugNoSpb.setEnabled)
        self.TrnRdbN.clicked['bool'].connect(self.AugNoLbl.setDisabled)
        self.TrnRdbN.clicked['bool'].connect(self.AugNoSpb.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(DatCrt)

    def retranslateUi(self, DatCrt):
        _translate = QtCore.QCoreApplication.translate
        DatCrt.setWindowTitle(_translate("DatCrt", "Dataset Creation"))
        self.TrnSetDef.setTitle(_translate("DatCrt", "Training Set Definitions"))
        self.TrnSetCSVLbl.setText(_translate("DatCrt", "Training Set Directory List CSV"))
        self.TrnCrtLbl.setText(_translate("DatCrt", "Create Training"))
        self.TrnSetCSVBtn.setText(_translate("DatCrt", "..."))
        self.TrnRdbY.setText(_translate("DatCrt", "Y"))
        self.TrnRdbN.setText(_translate("DatCrt", "N"))
        self.VldSetDef.setTitle(_translate("DatCrt", "Validation Set Definitions"))
        self.VldSetCSVBtn.setText(_translate("DatCrt", "..."))
        self.VldSetCSVLbl.setText(_translate("DatCrt", "Validation Set Directory List CSV"))
        self.VldCrtLbl.setText(_translate("DatCrt", "Create Validtion"))
        self.VldRdbY.setText(_translate("DatCrt", "Y"))
        self.VldRdbN.setText(_translate("DatCrt", "N"))
        self.TstSetDef.setTitle(_translate("DatCrt", "Test Set Definitions"))
        self.TstCrtLbl.setText(_translate("DatCrt", "Create Test"))
        self.TstSetCSVLbl.setText(_translate("DatCrt", "Test Set Directory List CSV"))
        self.TstSetCSVBtn.setText(_translate("DatCrt", "..."))
        self.TstRdbY.setText(_translate("DatCrt", "Y"))
        self.TstRdbN.setText(_translate("DatCrt", "N"))
        self.TagSet.setTitle(_translate("DatCrt", "Tagging Settings"))
        self.LblLstLbl.setText(_translate("DatCrt", "Label List (Seperate with Comma)"))
        self.GrpLstLbl.setText(_translate("DatCrt", "Group List (Seperate with Comma)"))
        self.KpDumCkb.setText(_translate("DatCrt", "Keep Labels with Dummy Data"))
        self.FrcTstCkb.setText(_translate("DatCrt", "Always Save Files from Test Sets"))
        self.ProcSet.setTitle(_translate("DatCrt", "Processing Settings"))
        self.AugNoLbl.setText(_translate("DatCrt", "Augmentation Number"))
        self.ProcNoLbl.setText(_translate("DatCrt", "Process Cores"))
        self.LblTypJS.setText(_translate("DatCrt", "JSON"))
        self.LblTypHM.setText(_translate("DatCrt", "HeatMap"))
        self.HMPeakLbl.setText(_translate("DatCrt", "HM Peak"))
        self.HMSeqLbl.setText(_translate("DatCrt", "HM Random"))
        self.HMSeqCkb.setText(_translate("DatCrt", "Sequential"))
        self.RndFlpCkb.setText(_translate("DatCrt", "Random Flipping"))
        self.RndFlpAxLbl.setText(_translate("DatCrt", "Random Flipping Axes"))
        self.RndFlpX.setText(_translate("DatCrt", "X"))
        self.RndFlpY.setText(_translate("DatCrt", "Y"))
        self.RndFlpXY.setText(_translate("DatCrt", "XY"))
        self.RndRotCkb.setText(_translate("DatCrt", "Random Rotating"))
        self.RndRotAgLbl.setText(_translate("DatCrt", "Random Rotating Angles"))
        self.OutSet.setTitle(_translate("DatCrt", "Output Settings"))
        self.ImgWLbl.setText(_translate("DatCrt", "Image Width:"))
        self.ImgHLbl.setText(_translate("DatCrt", "Image Height:"))
        self.OutDirLbl.setText(_translate("DatCrt", "Output Directory"))
        self.OutDirBtn.setText(_translate("DatCrt", "..."))
        self.StartButton.setText(_translate("DatCrt", "Start"))
        self.ExitButton.setText(_translate("DatCrt", "Exit"))
